### ISSUE TITLE
include FM7.sc

### ISSUE THREAD

**Issue by tehn** [lazzarello/fm7#1]
it'd be great to move Engine_FM7.sc out of `we` and into this repo. we'll then remove it from `we`

**Comment by lazzarello** [comment]
I made #3 to address this. I will need to coordinate with you since this is a breaking change.

**Comment by tehn** [comment]
it seems Engine_FM7.sc is already out of `we`

but `fm7.lua` is still there, which should be removed. i'll do that now.

go ahead and merge.
